### ISSUE TITLE
Image reference links inconsistent click area

### ISSUE THREAD

**Issue by garrying** [chainguard-dev/edu#1032]
**Describe the bug**

When a user clicks into `Chainguard Images`, `Reference`, and tries selecting an image from the expanded list, only the text is clickable and navigates to the image page. Compared to `Getting Started Guides`, navigation links like `PostgreSQL` the click area is the entire highlighted nav item area.

**To Reproduce**
1. Go to 'https://edu.chainguard.dev/'
2. Click on 'Chainguard Images'
3. Expand 'Reference'
4. Click on an image link highlighted area (not text)

**Expected behavior**
Clicking in the highlighted hover area will take the user to the image page.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 117.0.5938.132

**Comment by MindTooth** [comment]
Just noticed the same.  Seems that this occurs on all links almost.

I fixed it by removing padding on the `<button>` and adding the following to the `<a>`:
```css
width: 100%;
padding: 12px 0 12px 36px;
```

This a fix by no means.  Just wanted to see how I could fix it.
