### ISSUE TITLE
Plan for moving + updating IAM docs so they're less focused on Enforce

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1033]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:** 
n/a

**Description:**
IAM management is one of Chainguard's secret sauces. Right now our IAM docs are all housed under Enforce, but IAM is increasingly relevant to the Images product. 

Questions to answer:
* How hard would it be to update our IAM docs so they're less focused on Enforce
* Would it make sense to move these docs to under Images? If not, how can we separate them out from Enforce?

**Comment by ltagliaferri** [comment]
We need to keep in mind that the language around "Enforce" should be modified to include "Images" in the docs that move out of the Enforce bucket

**Comment by SharpRake** [comment]
Issued a [draft PR](https://github.com/chainguard-dev/edu/pull/1087) outlining the approach I'm thinking of. I was asked to prioritize this with the goal of wrapping up these changes before November 1, so I will be focusing on updating the docs in the new bucket this week.
