### ISSUE TITLE
Update docs for configuring custom IDP and IAM and Security

### ISSUE THREAD

**Issue by cmdpdx** [chainguard-dev/edu#1057]
Custom identity providers now require users configure a default role to grant to users when first logging in if they have not yet registered through that IDP. 

The user is bound to the role at the group where the custom IDP is defined. Typically this is the organization/root level. The default role can be a built in role (e.g. `viewer`) or a custom role defined in the same group or in an ancestor group.

A new flag, `--default-role` has been added to `chainctl iam identity-provider create` and `update`. For `create`, if the user omits the flag they will be asked to select a role interactively. Roles can be referenced by either ID or name. 

Users cannot configure a default role that has more capabilities than they do.

It also may be worth adding that users can set their verified org name with a single command, similar to setting `default.identity-provider`:

`chainctl config set default.org-name <org name>`

**Comment by SharpRake** [comment]
@cmdpdx Sorry for the delay with this - our IAM stuff was in a bit of a holding pattern until recently. I have a [PR open](https://github.com/chainguard-dev/edu/pull/1210) to resolve this.
