### ISSUE TITLE
Document quotas information

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1070]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:**

**Description:**

Per [this conversation](https://chainguard-dev.slack.com/archives/C03PJFT9Y1G/p1697153093912129), we ought to have information about Enforce quotas documented somewhere on Edu. I'm thinking this could potentially fit as an entry in the Enforce FAQ page but may deserve expansion into a full article.

**Comment by ltagliaferri** [comment]
I would add this to the Troubleshooting Tips
