### ISSUE TITLE
Remove 'Administration' bucket from Enforce docs

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1113]
**Is your feature request related to a problem? Please describe.**
We now have a fancy new top-level `Administration` bucket. It could be confusing for readers who navigate to the `Enforce` bucket and find another `Administration` bucket there.

**Describe the solution you'd like**
The docs within the `Enforce` => `Administration` bucket will get moved to other logical locations and I'll remove the bucket itself.

**Describe alternatives you've considered**
None really, this seems like the obvious solution!

**Additional context**

**Comment by ltagliaferri** [comment]
Draft PR: https://github.com/chainguard-dev/edu/pull/1126/
