### ISSUE TITLE
Improve Enforce docs structure

### ISSUE THREAD

**Issue by kimsterv** [chainguard-dev/edu#112]
Consider splitting the Enforce docs into sections:

- Enforce overview and architecture maybe
    - Signing images, creating sboms
        - Link to sigstore projects and docs 
        - Using signing keys vs. keyless
    - Cli vs web
    - Agent vs. agentless
    - Runtime enforcement vs continuous 
    - IAM, groups, invite codes 
- Getting started with enforce 
    - Prereqs / compatible k8s distros, versions, etc.
    - Signing up
    - Signing your images, making sboms
    - Setting up chainctl 
    - Sample policies
    - Applying policies to cluster
    - Viewing logs 
- Chainctl CLI detailed docs. Why do i need this and what does it do that i can’t do with kubectl
- Enforce web UI detailed docs - what do i use this for?
- Separately, quickstart tutorial

**Comment by ltagliaferri** [comment]
All the items listed are either published or in flight with their own tickets, so I will close this out.
