### ISSUE TITLE
Move Events Reference doc from Enforce to Administration bucket

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1124]
**What topic are you requesting a resource about?**
* Other (please describe)
Tracking work for moving Events Ref doc from Enforce to Admin bucket

**Description:**
I submitted a PR on `mono` to update the Events doc template to minimize Enforce references. Will update the action file and add a redirect here once the template changes are merged.

**Comment by ltagliaferri** [comment]
Waiting for mono release for this to be finalized
