### ISSUE TITLE
Failing to multistage build distroless image from wolfi-base

### ISSUE THREAD

**Issue by souovan** [chainguard-dev/edu#1200]
**Describe the bug**
I'm trying to follow the tutorial from https://edu.chainguard.dev/open-source/wolfi/wolfi-with-dockerfiles/ when i try to build the image an error occurs

```sh
=> ERROR [builder 2/6] RUN adduser -D nonroot                                       0.3s
------
 > [builder 2/6] RUN adduser -D nonroot:
#0 0.250 adduser: user 'nonroot' in use
------
Dockerfile:4
--------------------
   2 |
   3 |     ARG version=3.11
   4 | >>> RUN adduser -D nonroot
   5 |     WORKDIR /app
   6 |
--------------------
ERROR: failed to solve: process "/bin/sh -c adduser -D nonroot" did not complete successfully: exit code: 1
```

**Additional context**
I even tried to comment the add user line and remove the `--user` to install pip requirements, as follow on my Dockerfile:

```Dockerfile
FROM cgr.dev/chainguard/wolfi-base as builder

ARG version=3.11
#RUN adduser -D nonroot
WORKDIR /app

RUN apk add python-$version py${version}-pip

USER nonroot
COPY requirements.txt /app/
RUN  pip3 install -r requirements.txt

FROM cgr.dev/chainguard/python:latest

ARG version=3.11
WORKDIR /app

COPY --from=builder /home/nonroot/.local/lib/python${version}/site-packages /home/nonroot/.local/lib/python${version}/site-packages

COPY inky.py inky.png /app/

ENTRYPOINT [ "python", "/app/inky.py" ]
```

but i got the error below ( even changing the python lib path ) to `/usr/lib/python${version}/site-packages /usr/lib/python${version}/site-packages`

```py
Traceback (most recent call last):
  File "/app/inky.py", line 2, in <module>
    import climage
ModuleNotFoundError: No module named 'climage'
```

when i used the entire wolfi-base image to run the container and reproduce the steps i have success

**Comment by ltagliaferri** [comment]
Thank you for flagging, @amouat is working on an update to this. I think the main issue is that the latest Python image is now 3.12, so try updating those parameters first.

**Comment by amouat** [comment]
Yeah, I'm in the middle of updating this. It's much easier to use venv for a multi-stage build. Try the following:

```
FROM cgr.dev/chainguard/python:latest-dev as builder

ENV LANG=C.UTF-8
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="/inky/venv/bin:$PATH"

WORKDIR /inky

RUN python -m venv /inky/venv
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

FROM cgr.dev/chainguard/python:latest

WORKDIR /inky

ENV PYTHONUNBUFFERED=1
ENV PATH="/venv/bin:$PATH"

COPY inky.py inky.png ./
COPY --from=builder /inky/venv /venv

ENTRYPOINT [ "python", "/inky/inky.py" ]
```

**Comment by amouat** [comment]
@souvan either works. I didn't realise which guide you were following at first. I have an update for that guide as well. The main problem is you have to be explicit about your python version.

**Comment by souovan** [comment]
Thank you, i tested both ways and worked fine ! i'm closing the issue but as you said this guide https://edu.chainguard.dev/open-source/wolfi/wolfi-with-dockerfiles/ must be updated

**Comment by ltagliaferri** [comment]
This guide is updated now, thanks @souovan 

https://edu.chainguard.dev/open-source/wolfi/wolfi-with-dockerfiles/
