### ISSUE TITLE
what is **node** term referring to ??

### ISSUE THREAD

**Issue by viveksahu26** [chainguard-dev/edu#1333]
**Describe the bug**
Line says:
`The contents node is used to define allowed package sources` and
`The cmd node defines the image entry point command /bin/sh -l`. 

**To Reproduce**
1. Go to [blog](https://github.com/chainguard-dev/edu/blob/main/content/open-source/apko/getting-started-with-apko.md).
2. Go to [section](https://github.com/chainguard-dev/edu/blob/main/content/open-source/apko/getting-started-with-apko.md#step-2--build-a-test-image).
3. Scroll down to  1st and 2nd paragraph just below `wolfi-base.yaml` file.
4. See Line beginning with-  "The **cmd** node defines the image entry point command /bin/sh -l"

**Expected behavior**
My basic doubt is that "what is **node** term referring to". As in above paragraph `node` refers to `content`, which means it refers to section such as `content`.  Whereas just below para, it refers node to `cmd`. But I think it should refer to `entrypoint`. Therefore correct statement would be:
 `The entrypoint node defines the image entry point command /bin/sh -l`.  
 OR
`The entrypoint node defines the image command /bin/sh -l`.

**Comment by SharpRake** [comment]
Hello @viveksahu26, and thank you for raising this issue. 

It seems as though the code block in question was updated at some point but not all the relevant explanations were updated to suit the changes. I just updated the language in that resource: https://github.com/chainguard-dev/edu/pull/1340

Thanks again!
