### ISSUE TITLE
[Images] Include additional demonstration of SBOM and Signature features

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#134]
As suggested by @danpopnyc  :

We should include a demonstration / proof of the additional features built-in with Chainguard Images: SBOMs and Signatures. Currently the overview page has a CVE comparison graph that proves the point of "less CVEs", and we can add the commands to check and demonstrate the Sigstore queries for SBOM and container signatures:

```shell
COSIGN_EXPERIMENTAL=1 cosign verify cgr.dev/chainguard/nginx | jq
```
and

```shell
COSIGN_EXPERIMENTAL=1 cosign download sbom cgr.dev/chainguard/nginx | jq
```

The question is: is the Overview page the right place to include these, considering we also want to include the output and it can make the page very long? Should we have an additional page for these instructions that we can link from other places? With a separate page we may be able to use an interactive terminal (just an idea).

Cc @ltagliaferri @jamonation @SharpRake

**Comment by ltagliaferri** [comment]
This is done with provenance info in Images
