### ISSUE TITLE
"Introduction to Cosign" and "How to Install Cosign" Sorted to the Bottom

### ISSUE THREAD

**Issue by mohammed90** [chainguard-dev/edu#137]
**Describe the bug**
The "Introduction to Cosign" and "How to Install Cosign" navigation links are at the bottom of the list under the "Cosign" header.

**To Reproduce**
1. Go to https://edu.chainguard.dev/open-source/sigstore/
2. Scroll to the bottom
3. Click on "Cosign"
4. See the navigation list
5. Click on any of the items
6. See the navigation list under "Cosign" on the left

**Expected behavior**
The "Introduction to Cosign" and "How to Install Cosign" navigation links are at the top of the list under the "Cosign" header.

**Screenshots**

<img width="709" alt="image" src="https://user-images.githubusercontent.com/2636183/192052292-2ebee459-5e69-4457-be0f-1ab9a89153d6.png">

<img width="316" alt="image" src="https://user-images.githubusercontent.com/2636183/192052361-2cff9cbc-0c38-4eb0-8130-8ee51609e12a.png">

**Desktop (please complete the following information):**

N/A

**Smartphone (please complete the following information):**

N/A

**Additional context**
The fix is to adjust the `weight` in the front-matter of those 2 pages to be smaller than the rest. I just want to make sure you're all on board with this change and reasoning.

**Comment by ltagliaferri** [comment]
Thanks @mohammed90 — I agree with the change! I made some minor other reorg changes, too. I can't tag you as a reviewer, but let me know if you have any other thoughts on #138
