### ISSUE TITLE
Clarification for Networking page

### ISSUE THREAD

**Issue by jbayntun** [chainguard-dev/edu#1396]
A customer was confused if we had networking requirements for when an image was actually running (eg, does a running image call back to chainguard).  I propose the following addition to the intro section of:
https://edu.chainguard.dev/chainguard/administration/network-requirements/

`Chainguard images do not call Chainguard services while running, so no network changes would be required to the runtime environment.  See the Notes column for more info on each Hostname.`

**Comment by ltagliaferri** [comment]
Feel free to open a PR for this
