### ISSUE TITLE
Getting started with apko links to deprecated GH action

### ISSUE THREAD

**Issue by benmoss** [chainguard-dev/edu#141]
**Describe the bug**
The Getting Started with apko guide links to https://github.com/chainguard-dev/actions/tree/main/apko-build

> If you want to run apko on CI/CD pipelines built on top of GitHub Actions, check the [apko build action](https://github.com/chainguard-dev/actions/tree/main/apko-build) on GitHub.

It looks like that's [deprecated](https://github.com/chainguard-dev/actions/blob/f35d004df8b9245d867eeff1ec72d67ed9eef2a8/apko-build/action.yaml#L77)

**Comment by erikaheidi** [comment]
working on it!
