### ISSUE TITLE
go-fips image page should add more info

### ISSUE THREAD

**Issue by xnox** [chainguard-dev/edu#1421]
**Is your feature request related to a problem? Please describe.**
go-fips image description does not clarify what one has to do to ensure binaries produced by that toolchain are in FIPS mode.

**Describe the solution you'd like**
@xnox should improve the docs based on internal spec they wrote

**Describe alternatives you've considered**
Information on how to build and verify go binaries are operating in FIPS mode should all be public

**Additional context**
As mentioned on slack

**Comment by mamccorm** [comment]
Adding some historical context - Previously we'd no way of rendering private image documentation in our image catalogue (assume same for Academy). We've also no monopod implementation today for our private-images repo.

I believe in the absence of above, the public facing docs would instead render the public image docs for fips variants. However now we have the ability to add private docs and have them rendered in the image catalogue / academy :) 

I'm not sure this ticket makes sense for edu? this seems more like an engineering quality issue? i.e go back and create some private docs that are missing for go-fips
