### ISSUE TITLE
How to add custom modules to Caddy Image?

### ISSUE THREAD

**Issue by rajasekhar-gundala** [chainguard-dev/edu#1500]
Hello,
Thank you very much for the project.

I am searching for documentation to add custom modules to [Caddy Image](https://images.chainguard.dev/directory/image/caddy/versions). We need DNS modules (like Cloudflare) in order to get SSL certs.

I know how to extend the base [Caddy Image](https://hub.docker.com/_/caddy) with custom modules. There is a section called ***Adding custom Caddy modules*** explains how to achieve it.

Can you please guide me how to add custom modules to [Caddy Image](https://images.chainguard.dev/directory/image/caddy/versions)?

**Comment by ltagliaferri** [comment]
If this is still an issue, I would raise it in the [Chainguard Images repo](https://github.com/chainguard-images/images/issues). This repo is for documentation.
