### ISSUE TITLE
Update maven example to handle "cannot create resource output directory" error

### ISSUE THREAD

**Issue by noelmcloughlin** [chainguard-dev/edu#1538]
**Describe the bug**

Maven-resources-plugin cannot create resource output directory (`/home/build/target/`) because maven lacks permissions to remove subdirectories under /home/build/ ([see similar issue](https://stackoverflow.com/q/53342060)).  

**To Reproduce**
1. Open terminal as some  random user
2. Follow https://edu.chainguard.dev/chainguard/chainguard-images/reference/maven#springboot until you execute this command:
``` 
docker run --platform=linux/amd64 --rm -v ${PWD}:/home/build cgr.dev/chainguard/maven:openjdk-17 clean install
```
3. See error from maven-resources-plugin

**Expected behavior**

This worked for me:
```
chmod o+w ../demo
docker run --platform=linux/amd64 --rm -v ${PWD}:/home/build cgr.dev/chainguard/maven:openjdk-17 clean install
chmod o-w ../demo     # optional, its just demo
```

**Comment by ltagliaferri** [comment]
Thanks for flagging this, I copied this over to the Images repo, where the readmes live. https://github.com/chainguard-images/images/issues/2624
