### ISSUE TITLE
Log4Shell demo tutorial

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#154]
Putting together a tutorial that walks readers through running a sample app that includes a vulnerable version of Log4j.

**Comment by kimsterv** [comment]
There's a new vulnerability that's similar "text4shell" and I believe @johnfosborneiii has done some prototyping for a demo. There's a blog post in the works [here](https://docs.google.com/document/d/14lZfD13VyUwoYzZClrpsG56jhZ1WJR6nW807lBB6s9o/edit). It might make sense to "genericize" this tutorial a bit if a similar workflow could be used for text4shell.

**Comment by dlorenc** [comment]
Is this issue still relevant?

**Comment by SharpRake** [comment]
@dlorenc Yes, there is [a draft for this tutorial](https://github.com/chainguard-dev/edu/pull/177) in the home stretch of review. I expect it to be published next week, at which point I'll close this issue
