### ISSUE TITLE
Resource: Document terraform defaults

### ISSUE THREAD

**Issue by jedsalazar** [chainguard-dev/edu#159]
**What topic are you requesting a resource about?** Enforce Terraform Provider 
* Chainguard product - Enforce
* Open source related - No
* Conceptual security related - No
* Other (please describe) 

**Proposed title:**
EKS Enforce Settings or something sufficiently vague 😂

**Description:**
Our [terraform provider](https://github.com/chainguard-dev/Block-Phase1/tree/main/terraform-provider) contains a lot of useful settings like impersonation values for AWS. There are also values for roles and the capabilities that we should document so folks who don't use our terraform provider can set manually.

Eventually I think we'll want further docs on the terraform provider once it's public

**Comment by ltagliaferri** [comment]
After discussion with @SharpRake, @nsmith5, and @jedsalazar it sounds like this is no longer needed so I am going to close this out. We can revisit if we need some Terraform resources in the future, maybe as part of Enforce FAQ or Overview.
