### ISSUE TITLE
Thanos latest sidecar bug. 

### ISSUE THREAD

**Issue by cgibbs35** [chainguard-dev/edu#1605]
**Describe the bug**
when deploying thanos as a sidecar with the sidecar configuration, the reloader was never triggering resulting in a prometheus crashback loop. 

**To Reproduce**
deploy prometheus community helm chart using chainguard latest images. following these directions. [here](https://github.com/thanos-io/thanos/blob/main/tutorials/kubernetes-helm/README.md)

using both chainguard latest for prometheus and thanos results in failure, however switching the thanos image back to the standard quay image the reloader config works and prometheus starts up. 

**Expected behavior**
both pods should start up and thanos sidecar should be deploying its reloader configs to rebuild the prometheus.yml for prometheus to startup

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cgibbs35** [comment]
this is related to a thanos regression [ here](https://github.com/thanos-io/thanos/issues/7400)

**Comment by ltagliaferri** [comment]
This repo is only for Chainguard Academy, I created a new issue in the `chainguard-images/images` repo, linked here. Thanks!
