### ISSUE TITLE
docs: Missing non-dev image details for glibc-dynamic image

### ISSUE THREAD

**Issue by bala-chainguard** [chainguard-dev/edu#1620]
Missing the non-dev image details here - 
https://edu.chainguard.dev/chainguard/chainguard-images/reference/glibc-dynamic/image_specs/

![2024-06-13_10-57-03](https://github.com/chainguard-dev/edu/assets/144775325/9d74421d-f407-48a1-862e-a2e526710dcc)

Glibc-dynamic details page should be similar to this Go image

![2024-06-13_10-58-44](https://github.com/chainguard-dev/edu/assets/144775325/55587b2a-1a06-461e-a931-243988850461)

**Comment by ltagliaferri** [comment]
We are turning down these pages on Academy next cycle. All reference docs will be in the public directory and console. I don't know that they will ingest the metadata.
