### ISSUE TITLE
Document "break glass" mode

### ISSUE THREAD

**Issue by kimsterv** [chainguard-dev/edu#166]
Add documentation for the recommended way for customers to "break glass" and turn "off" Chainguard Enforce. in case of an incident response. Removing the namespace label is the recommended approach today.

**Comment by ltagliaferri** [comment]
https://github.com/sigstore/policy-controller/pull/248

What is a proposed title for this document, is it "Handling incident responses in Chainguard Enforce" with "break glass" in the keywords?

**Comment by tcnghia** [comment]
I guess the document should say "how to quickly disable policy enforcement", as I am not sure we need to do so for every incident responses.  cc @johnfosborneiii to put in more context.

I am also confused a bit by the wording of "break glass". Usually it means going to "advanced" usage mode (for example, SSH-ing into a GKE Node). I suspect it will confuse other users as well so I'm not sure we should say "break glass" at all in the doc?

**Comment by kimsterv** [comment]
Not using the term "break glass" sgtm. We can be clear and use the language Nghia suggested.

**Comment by ltagliaferri** [comment]
Thanks @tcnghia and @kimsterv

**Comment by johnfosborneiii** [comment]
Agree on not using the term break-glass, too ambiguous for docs, good point @tcnghia

**Comment by ltagliaferri** [comment]
https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/how-to-disable-policy-enforcement/
