### ISSUE TITLE
Bug: Monospaced links in dark mode are visually indistinguishable

### ISSUE THREAD

**Issue by mcaveety** [chainguard-dev/edu#1707]
**Describe the bug**
On the Academy, we have some monospaced text which also serves as a link. In light mode, both the monospacing and the light-blue color telltale of a link is visible as well. However, when you switch to dark mode, the coloring disappears and you cannot determine it is a link without hovering over the monospaced text. I don't suspect this is an issue in most cases, but a recent article I published has this issue.

**To Reproduce**
1. Go to https://edu.chainguard.dev/chainguard/chainguard-images/working-with-images/compiled-programs/
2. Navigate to the `wolfi-base` image section
3. Observe that, in light mode, the text appears as both monospaced and a link.
4. Switch the site to dark mode
5. Observe that, in dark mode, the text only appears as monospaced, though the link still functions

**Expected behavior**
I would expect that in either dark or light mode, the text still appears as blue. I understand that in dark mode the text becomes white, which is likely why this occurs. Though, it makes monospaced links visually impossible to detect, and you'd need to hover over to figure out it actually links anywhere. 

**Screenshots**
Light mode: 
<img width="639" alt="Screenshot 2024-07-23 at 9 34 11 AM" src="https://github.com/user-attachments/assets/87003526-7896-4756-9a2d-ccde4ce972d8">
Dark mode: 
<img width="629" alt="Screenshot 2024-07-23 at 9 35 08 AM" src="https://github.com/user-attachments/assets/449f8e42-d15c-4e0c-97d6-7e961b70fdb1">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Browser Google Chrome
 - Version 126.0.6478.183 (Official Build) (arm64)

**Additional context**
I actually ran into this issue myself without realizing it -- I was confused, when in testing, sometimes the links would appear visibly and other times it wouldn't. If I had to guess, I imagine switching to dark mode would cause all text to turn white and it overrides the link color. 🤷

**Comment by smythp** [comment]
Thanks, good issue. I'll take a look as part of https://github.com/chainguard-dev/internal/issues/4072
