### ISSUE TITLE
Update Security Advisories doc to show advisory event types

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1739]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:**
n/a (update to existing doc)

**Description:**
It was suggested that we document these Security Advisories event types on Academy: https://github.com/wolfi-dev/advisories/blob/main/docs/event_types.md

It makes sense to add this info to the Security Advisories doc: https://edu.chainguard.dev/chainguard/chainguard-images/working-with-images/security-advisories/

per Adrian "Yeah, we can just add a section before comparing images or an appendix I think"

slack context: https://chainguard-dev.slack.com/archives/C040R8V1BG9/p1722614091906239

**Comment by sheesh** [comment]
@SharpRake I took this off the 24h board, but let me know if you think it should go back on. Thanks!

**Comment by SharpRake** [comment]
My mistake - I meant to close this issue as @mcaveety published this article a few hours after I first created this issue: https://edu.chainguard.dev/chainguard/chainguard-images/working-with-images/security-advisories/how-chainguard-issues/#summary-of-advisory-statuses
