### ISSUE TITLE
update envoy-ratelimit image README

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1766]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:** n/a

**Description:**
our [envoy-ratelimit image's README](https://images.chainguard.dev/directory/image/envoy-ratelimit/overview) has one URL that's 404-ing. I think it could use a quick tune up as I update one or more other images.

slack ref: https://chainguard-dev.slack.com/archives/C03H64P08UT/p1723650616360719

**Comment by SharpRake** [comment]
This is done, just needs to be approved + merged here: https://github.com/chainguard-images/images-private/pull/4767

**Comment by smythp** [comment]
Instead of

`https://console.enforce.dev/images/catalog`

should we do

`https://console.chainguard.dev/images/public`

or 

`https://console.chainguard.dev/overview`

**Comment by SharpRake** [comment]
this is done: https://github.com/chainguard-images/images-private/pull/4787
