### ISSUE TITLE
Update "How to Use Chainguard Security Advisories" chainctl examples

### ISSUE THREAD

**Issue by mcaveety** [chainguard-dev/edu#1772]
[Taking a look at the commands used in this guide](https://edu.chainguard.dev/chainguard/chainguard-images/working-with-images/security-advisories/how-to-use/), the `chainguard-private` organization is referenced frequently. This organization isn't accessible to anyone outside of Chainguard so this needs to be updated, likely to a freely available example (such as the `chainguard` organization).

Link to an example command: https://edu.chainguard.dev/chainguard/chainguard-images/working-with-images/security-advisories/how-to-use/#so-youve-encountered-a-cve-in-a-chainguard-image:~:text=docker%20scout%20cves%20cgr.dev/chainguard%2Dprivate/go%3A1.21.2

Because the guide builds upon this starting example, it will take a bit of work to replace all references to it. It's also worth noting that the freely available Go images don't include version tags like :1.21.2 so these references would need to be changed to :latest and the digest of an older, freely available version of the :latest image used instead.

**Comment by ltagliaferri** [comment]
It looks like this was updated to remove `chainguard-private`. I am not worried about the version example as this is for those who have their own directory of images.
