### ISSUE TITLE
Updates to Academy colors and fonts

### ISSUE THREAD

**Issue by mcaveety** [chainguard-dev/edu#1774]
Hey, @smythp !
Unfortunately, I won't have a chance to tackle this before I head out today. I'm going to compile a list of things that I noticed on the Academy which might warrant an update. I suspect these are lingering from the old site theme.

### Colors:
In dark mode, the tags, monospaced text, and selected article colors are still the same dark grey color from the old theme.
<img width="658" alt="Screenshot 2024-08-16 at 12 56 02 PM" src="https://github.com/user-attachments/assets/b281a892-45d9-4356-b72a-30e3adf3c326">

A similar case is seen with the copy-and-paste code blocks in our tutorials:
<img width="843" alt="Screenshot 2024-08-16 at 12 56 56 PM" src="https://github.com/user-attachments/assets/0bd9d197-a27d-4d8d-9af9-fc2d246740f8">

Same is true for tables:
<img width="1180" alt="Screenshot 2024-08-16 at 12 57 35 PM" src="https://github.com/user-attachments/assets/c2039dc7-f1f8-475c-a5c6-3fb9651e3923">

There are thin, grey bars that remain from the old color theme. Also around the prev->next buttons. Super hard to pick out, but I think they should be neon purple.
<img width="1512" alt="Screenshot 2024-08-16 at 1 03 11 PM" src="https://github.com/user-attachments/assets/f0e7d9fb-5cad-400a-8b10-e0d230276a30">

Chart colors could do with a refresh...
<img width="832" alt="Screenshot 2024-08-16 at 1 02 02 PM" src="https://github.com/user-attachments/assets/539c3014-326b-4414-8a37-b225a12f5a32">

There are also these numbered blocks on this article, https://edu.chainguard.dev/software-security/cves/cve-remediation/
<img width="259" alt="Screenshot 2024-08-16 at 1 04 25 PM" src="https://github.com/user-attachments/assets/c25ca6d3-f4f6-41ac-b66d-563f49fd5000">

### Fonts / Text:
Code blocks no longer have text explaining what type of content they are. There used to be a "heading" to each code block with the content type (ex. sh, Dockerfile, Python, etc.) These content types were pulled from the markdown:
\```Dockerfile
....
or 
\``` Python
...

I could have sworn that a default font was displaying somewhere, but I think it was in the case of the above example... so if that functionality is gone, then the incorrect font went with it.

You've done such an incredible job on this effort, I by no means am trying to be nitpicky or critical of your work. I would have loved to jump on these changes if I had another week. The color palette thing is super tricky now that we're working with a purpleish base color, especially on dark mode. I strongly feel that the color palette needs to be expanded so that you have more flexibility. The old theme had many shades of grey that helped with these changes, but we've been using the secondary and tertiary colors with much difficulty. 🤷 just my thoughts on that. 

Do what you wish with these suggestions! Do not hesitate to counter them, ignore them, etc. I'm mainly dumping this here for tracking since I won't have the opportunity to work on it myself.

**Comment by smythp** [comment]
No, these need a fix, I appreciate your pointing them out and I'll create a backlog item with these. The code heading really needs to come back as the most urgent item. Thanks for this, Michelle! I really appreciated your above-and-beyond attitude and your cheerful competence during your time with us this summer. Hope we get to work together again.
