### ISSUE TITLE
Kafka need bitnami updates

### ISSUE THREAD

**Issue by johnfosborneiii** [chainguard-dev/edu#1780]
Since Kafka 3.6 Chainguard  has been building the kafka image to be bitnami compat which has a different entrypoint and directory structure but the current docs still reference the non-bitnami (versions < 3.6) usage:
https://images.chainguard.dev/directory/image/kafka/overview

**Comment by sheesh** [comment]
Thanks, @johnfosborneiii. Adding this to our list. 
@SharpRake, tagging this as 24i so we can consider it for next cycle.

**Comment by SharpRake** [comment]
I've been playing with the kafka Image since the summit and have been having some trouble pinning down how exactly it's supposed to work. John O gave me some tips but I may need to reach out for more help.

**Comment by johnfosborneiii** [comment]
I'd just simplify the docs to show them how to use the helm values that we test with https://github.com/chainguard-images/images/blob/main/images/kafka/tests/main.tf

**Comment by SharpRake** [comment]
Checked in with John Osborne about this README today. He let me know that my draft is on the right track, hoping to have an updated README ready for review by EOD today.
