### ISSUE TITLE
Latest images pulled from Docker registry are out of date

### ISSUE THREAD

**Issue by keatsk** [chainguard-dev/edu#1785]
When I pulled the latest redis-cluster-bitnami image today (26-Aug-2024) using:
`docker pull cgr.dev/chainguard/redis-cluster-bitnami:latest`
I get an image from 5 months ago with a large number of vulnerabilities.

Is there a problem with your publishing pipeline?

Thanks in advance.

**Comment by ltagliaferri** [comment]
Thanks for raising this, I moved this to the Chainguard Images repo as this repo is just for the docs site: https://github.com/chainguard-images/images/issues/2941
