### ISSUE TITLE
DOCS ISSUE UPDATE: Artifactory Pull Through Instructions

### ISSUE THREAD

**Issue by ericbannon** [chainguard-dev/edu#1789]
**Describe the bug**
https://edu.chainguard.dev/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/

The documentation here needs to be corrected in the following location:

https://edu.chainguard.dev/chainguard/chainguard-registry/pull-through-guides/artifactory-pull-through/#testing-pull-through-of-a-chainguard-production-image

``` 
docker pull <myproject>.jfrog.io/cgr-private/<example.com>/chainguard-base:latest
```

"Be sure the docker pull command you run includes the name of your artifactory project and the name of your organization’s registry. Additionally, if you entered a different repository key in the setup section, use it in place of cgr-private."

You should NOT include the name of the registry (i.e. example.com). The pull token used in the remote repository steps automatically authenticates to the correct customer registry and this will not work.

The correct pull path would be 

```
docker pull <myproject>.jfrog.io/cgr-private/chainguard-base:latest
```

We should call this out and change these instructions in the documentation otherwise customers will receive a "manifest unknown" error when trying to pull after setup

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sheesh** [comment]
Hey @ericbannon! Thanks for this! I noticed you closed this issue, but the fix hasn't been made yet. Should we still consider this a bug, or does it no longer need to be addressed? cc @SharpRake

**Comment by ericbannon** [comment]
Lets hold off - it may not be a bug

**Comment by sheesh** [comment]
Gotcha, thanks!

**Comment by ericbannon** [comment]
So we figured out what was wrong. We need to add additional documentation that includes instructions for use of Virtual repositories in Artifactory. 

When you are using the main artifactory instance the current docs are correct, but when using virtual you MUST exclude the remote-repo-key from the image path. The virtual repo proxies this so its not needed.

Example:

Without Virtual Repo:
cbre.chainguard.jfrog.io/cbre-private/cbre.com/go

where cbre.chainguard.jfrog.io is the main artifactory instance, cbre-private is the remote repo key, and cbre.com is their private registry in cgr.dev

WITH virtual repo this changes to:

pull chainguard.jfrog.io/cbre/cbre.com/go:1-22

Where cbre is the virtual repo repository key (not the remote). In other words, the remote repository key of cbre-private is not needed in this case

CBRE is the prospect here but many others may run into this
@sheesh

**Comment by sheesh** [comment]
Thanks! We'll prioritize this.
