### ISSUE TITLE
CO "Supply Chain Security Fundamentals" course updates

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#1803]
This is an issue for implementing feedback given by reviewers from CS and other teams. 

Feedback can be found in this thread in the temp-customer-onboarding channel:https://chainguard-dev.slack.com/archives/C07BF1VRL1E/p1725476038771929

Make sure to also check the Google Doc ([in the customer onboarding spreadsheet](https://docs.google.com/spreadsheets/d/1Pv15Z-CrHb7CK6mtpBlHgWOsmcRLRDyPCAc7rQZ9kNQ/edit?gid=1642731768#gid=1642731768)) for each article to see if there is any additional feedback.

**Comment by ltagliaferri** [comment]
CO course is now complete ✅
