### ISSUE TITLE
Console docs update to list Labels and Annotations

### ISSUE THREAD

**Issue by anitapower** [chainguard-dev/edu#1837]
**What topic are you requesting a resource about?**
Request to add OCI labels here: https://console.chainguard.dev/images/organization/image/apko/specifications 
and/or a docs page perhaps explaining the differences between Labels and Annotations.

OCI [spec](https://specs.opencontainers.org/image-spec/annotations/) on Annotations.

* Chainguard product: Images

* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:**

**Description:**
 more context here:
**[](https://chainguard-dev.slack.com/archives/C04PYHWPE1F/p1725274582490199)**

**Comment by SharpRake** [comment]
After discussing this with my team we feel a doc on OCI specs would be outside of Academy's scope. Instead we recommend sharing these resources with customers as needed: 

* [Annotations and Labels in Container Images](https://adrianmouat.com/posts/annotations-and-labels-in-container-images/) from Adrian's personal blog
* [How and when to use Docker labels / OCI container annotations](https://snyk.io/blog/how-and-when-to-use-docker-labels-oci-container-annotations/) from Snyk's blog

Closing this issue, but let me know if there's anything else I or my team can help with this.
