### ISSUE TITLE
Remove Contributors page

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#1882]
The [contributors page](https://edu.chainguard.dev/contributors) isn't maintained and doesn't serve a clear purpose. We also don't link to it from the Academy homepage, which makes me wonder why we have it at all. 

We can delete this issue if there's a strategy or purpose behind the Contributors page that I'm unaware of, but otherwise we should look into removing it.

**Comment by ltagliaferri** [comment]
If it's not bothering anyone, I would like to leave the functionality there in case we want to use it in the future. Are there any negative affects of it?

**Comment by SharpRake** [comment]
I'm fine with keeping it! Will close this issue.
