### ISSUE TITLE
Update Getting Started with the Go Chainguard Image

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#1891]
Update [Getting Started with the Go Chainguard Image](https://edu.chainguard.dev/chainguard/chainguard-images/getting-started/go/).

### Maintenance Sprint 2024.1
This issue is part of the [Maintenance Sprint 2024.1](https://github.com/chainguard-dev/edu/issues/1889). Check the [Supporting Doc](https://docs.google.com/document/d/1Cy4WWUHu_WE365tNqBiYBFQ8Y-OJtrdHUf2kBftq85c/edit?pli=1&tab=t.0) for guidance and what to look for when updating Academy articles.

**Comment by erikaheidi** [comment]
Starting to work on this.

**Comment by smythp** [comment]
I just updated the Go README in case there's anything useful in there

https://images.chainguard.dev/directory/image/go/overview

**Comment by erikaheidi** [comment]
> I just updated the Go README in case there's anything useful in there
> 
> https://images.chainguard.dev/directory/image/go/overview

This is great! I think the demos you have there are more interesting and cover more use cases, so I closed the PR I had open with the basic demo and will rewrite the guide based on your demos, if that's ok.

**Comment by smythp** [comment]
Glad you think they're useful. I like to nerd out a little on the examples for languages I'm somewhat familiar with. Use as much as you want :)

**Comment by erikaheidi** [comment]
The new demos from Patrick are now in the edu-images-demos repo, I'm now working on the guide updates.

**Comment by erikaheidi** [comment]
PR open for review by @SharpRake 

https://github.com/chainguard-dev/edu/pull/1945

**Comment by erikaheidi** [comment]
PR merged 👍🏼 closing this now
