### ISSUE TITLE
Update Getting Started with the Cilium Chainguard Images

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#1897]
Update [Getting Started with the Cilium Chainguard Images](https://edu.chainguard.dev/chainguard/chainguard-images/getting-started/cilium/).

### Maintenance Sprint 2024.1
This issue is part of the [Maintenance Sprint 2024.1](https://github.com/chainguard-dev/edu/issues/1889). Check the [Supporting Doc](https://docs.google.com/document/d/1Cy4WWUHu_WE365tNqBiYBFQ8Y-OJtrdHUf2kBftq85c/edit?pli=1&tab=t.0) for guidance and what to look for when updating Academy articles.

**Comment by matthewhelmke** [comment]
https://github.com/chainguard-dev/edu/pull/1936

**Comment by matthewhelmke** [comment]
Done
