### ISSUE TITLE
Update Getting Started with the Chainguard Istio Images

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#1900]
Update [Getting Started with the Chainguard Istio Images](https://edu.chainguard.dev/chainguard/chainguard-images/getting-started/istio/).

### Maintenance Sprint 2024.1
This issue is part of the [Maintenance Sprint 2024.1](https://github.com/chainguard-dev/edu/issues/1889). Check the [Supporting Doc](https://docs.google.com/document/d/1Cy4WWUHu_WE365tNqBiYBFQ8Y-OJtrdHUf2kBftq85c/edit?pli=1&tab=t.0) for guidance and what to look for when updating Academy articles.

**Comment by matthewhelmke** [comment]
I'm closing this with a link to an issue that supercedes this. https://github.com/chainguard-dev/internal/issues/4498
