### ISSUE TITLE
Update How to use Chainguard Security Advisories and the Diff API

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#1901]
Update [How to use Chainguard Security Advisories and the Diff API](https://edu.chainguard.dev/chainguard/chainguard-images/videos/security_advisories/).

### Maintenance Sprint 2024.1
This issue is part of the [Maintenance Sprint 2024.1](https://github.com/chainguard-dev/edu/issues/1889). Check the [Supporting Doc](https://docs.google.com/document/d/1Cy4WWUHu_WE365tNqBiYBFQ8Y-OJtrdHUf2kBftq85c/edit?pli=1&tab=t.0) for guidance and what to look for when updating Academy articles.

**Comment by smythp** [comment]
I'm likely to bump this given the midstream edu platform work that has come up. I'll keep it around for now in case I can get to it.

**Comment by smythp** [comment]
Bumped a README instead, PR out for this
