### ISSUE TITLE
Headless Login Documentation

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#194]
"Login flow from another device"

Add paragraph on device flow 

[Issue](https://github.com/chainguard-dev/internal/issues/730)

[PR](https://github.com/chainguard-dev/mono/pull/5254)

**Comment by ltagliaferri** [comment]
When you open browser on another device (phone, etc.)

```
[ 16:43:49 ] colin in ~/code/chainguard/mono/chainctl on device-flow
 λ ./chainctl auth login
Authenticating...
Error opening browser. Switching to device flow...

Enter the verification code FTFD-ZVTV in your browser at: https://auth.chainguard.dev/activate
Code will be valid for 900 seconds
Token received!
Successfully exchanged token.
Valid! Id: af641...
```

**Comment by jamonation** [comment]
I've got a partially working PR open to make device flow use a flag like `--device-flow` explicitly as well. This flag will ensure that Google Cloud, AWS, etc. metadata endpoints get bypassed for auth.
