### ISSUE TITLE
Ports and Protocols reference documentation

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#197]
Chainguard Enforce ports, protocols, and domains for firewalls and proxy configuration — all the components and permissions (and what to open from a firewall perspective)

`chainctl` config reference — noproxy, http, https, openapi

Potentially can be automated 

Might also be able to include things like K8s service accounts, cluster roles, and cluster role bindings for reference, too

cc @jedsalazar

**Comment by danpopnyc** [comment]
an overall system requirements for Enforce Agent/Agentless is a big requirement for quicker time to value.  we have a prospect asking for this (Boxboat and Duke) 

i.e. https://docs.sysdig.com/en/docs/administration/on-premises-deployments/architecture-system-requirements/system-requirements/ 



we should prioritize this.

**Comment by ltagliaferri** [comment]
There is some discussion on https://github.com/chainguard-dev/customer-issues/issues/18 regarding ports, to

>BoxBoat have requested a list of ports for Duke Energy. They're looking to start early January but would be good if I could confirm the ports prior to speaking with BoxBoat. Is the AMEX example still valid?
>Duke are looking to trial the SaaS first, and then potentially On-Prem, am I right in assuming the port requirements will be different with the two implementations?

**Comment by joshrwolf** [comment]
leaving refs to past work here re: required proxy vars - https://github.com/chainguard-dev/mono/issues/5986

**Comment by ltagliaferri** [comment]
Updated priority due to this [thread](https://chainguard-dev.slack.com/archives/C02GS1U8L8L/p1674766763434859)

**Comment by ltagliaferri** [comment]
In progress: https://docs.google.com/spreadsheets/d/11EKCWGhepcMy_KiFri3QsDc3Wp3EErkSO-PYBG1ogFE/edit#gid=0

**Comment by jamonation** [comment]
Basic ports and protocols doc is up here: https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements/

Next iteration of the page needs to add any extra firewall rules that are required for GKE/EKS public clusters.

**Comment by k4leung4** [comment]
almost done

**Comment by jamonation** [comment]
I think this is OK to close off. I'll make separate issues for different cloud providers if anyone reports network/firewall issues.
