### ISSUE TITLE
Dan has a ton of content on medium that we should try to re-use on our academy site

### ISSUE THREAD

**Issue by kimsterv** [chainguard-dev/edu#217]

**Comment by ltagliaferri** [comment]
https://dlorenc.medium.com/

We should ask for permission of course :)

**Comment by sheesh** [comment]
Doc with audit notes here: https://docs.google.com/document/d/11kp8Wve3c_w-qcLtHj3XO18aEsTinxGkTf57fjM4M3U/edit#

I'm going to begin a rewrite of the OCI Artifacts Explained post as a test case. 

Dan has approved!

**Comment by sheesh** [comment]
Audit complete. Writing new OCI article that pulls from one of Dan's post as first test case. New ticket created.
