### ISSUE TITLE
Information Architecture Audit

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#219]
With increased docs and articles across Chainguard Academy, we should be thinking about how to make the information architecture more user friendly

**Comment by ltagliaferri** [comment]
Work in progress: https://docs.google.com/presentation/d/1N-0eW2WXBMrYyQ3dc7QpzHuuPGhY4YfxiGSETnghL4E/edit#slide=id.g1929e4c1f25_0_196

**Comment by sheesh** [comment]
Shared presentation with Kim and team and established general buy in.

Deck: https://docs.google.com/presentation/d/1N-0eW2WXBMrYyQ3dc7QpzHuuPGhY4YfxiGSETnghL4E/edit#slide=id.g1c5abfedb7d_0_514

Next step, creating a requirements doc and evaluating the current Hugo theme to see where and how we might need additional help.
