### ISSUE TITLE
Documentation for Rego support

### ISSUE THREAD

**Issue by tcnghia** [chainguard-dev/edu#223]
**Is your feature request related to a problem? Please describe.**

We just added Rego support in Enforce for K8s, but we currently don't have documentation on our edu site yet.

**Describe the solution you'd like**

We document on our edu site:
- How to use this feature
- Some examples

**Additional context**
https://github.com/chainguard-dev/customer-issues/issues/88

**Comment by tcnghia** [comment]
Engineering contacts: cc @hectorj2f, @vaikas who added this support. Also @joshrwolf who is working on policies processing in Enforce.

**Comment by kimsterv** [comment]
Here's the blog post https://www.chainguard.dev/unchained/getting-started-with-rego-policies

**Comment by ltagliaferri** [comment]
Implemented updates and under review in #251

**Comment by dlorenc** [comment]
Looks in progress :)

**Comment by tcnghia** [comment]
https://github.com/chainguard-dev/edu/pull/251 merged, I think this is done now.
