### ISSUE TITLE
How to hook up to Slack or Jira with Chainguard Enforce Events tutorial

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#229]
Include section on Cloud events authorization:

**What topic are you requesting a resource about?**
* Enforce

**Proposed title:**
How to Authenticate Incoming Enforce Cloudevents

**Description:**

We need a page with details on how to verify the `Authorization: bearer ....` token that comes with cloud events from Enforce.

**Comment by jamonation** [comment]
https://github.com/chainguard-dev/enforce-events/tree/main/slack-webhook is a good reference for the Slack integration piece.

**Comment by ltagliaferri** [comment]
Related [thread](https://chainguard-dev.slack.com/archives/C02SD39C6BW/p1675177346346029)

**Comment by jamonation** [comment]
Tutorial in linked PR #606  for part 1 of this - creating Github issues.

I'll create another for Slack as part of this issue.

**Comment by jamonation** [comment]
Next part is a tutorial for slack messages in PR #607
