### ISSUE TITLE
"What Makes a Good SBOM?" Page is Not Showing Up

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/edu#249]
**Describe the bug**
The "what makes a good sbom?" page is not showing up.

**To Reproduce**
![Screenshot 2023-01-05 at 12 54 26 PM](https://user-images.githubusercontent.com/54914994/210847734-dafc8b36-74c8-436d-b057-cce0d58a2174.png)

**Expected behavior**
There should be a link to a "what makes a good sbom?" page.

**Desktop (please complete the following information):**
 - OS: MacOS, M1, Ventura 13.0.1
 - Browser: Brave Version 1.44.112 

**Additional context**

PR #246 merged and was supposed to have added a page. I probably did something wrong. Sorry! Help appreciated.

**Comment by jspeed-meyers** [comment]
Did I need to explicitly add something somewhere to make this page show up in the dropdown?

**Comment by ltagliaferri** [comment]
We specifically added the other one to the dropdown in the menu file here: https://github.com/chainguard-dev/edu/blob/main/config/_default/menus/menus.en.toml but we could make a more generic "software security" landing page. I also was wondering if you thought an SBOM section would make the most sense under "open source" instead? Once we have more SBOM material we can also move things around

**Comment by jspeed-meyers** [comment]
Ah, good point. I defer to you, but, on second thought, perhaps this does make more sense in "open source." Should I put in a PR that modifies this toml file and moves the asset to the correct location within "open source"?
