### ISSUE TITLE
Audit docs that reference policies

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#258]
https://chainguard-dev.slack.com/archives/C02SD39C6BW/p1673391261697799

Following up on my AI from earlier, I added a call to Validate() to check that all of our policies in the catalog are warning/error free, in particular this addresses the missing issue/subject problem that will break next release, but to add the check I also needed to make some of the public keys ~real, so wanted to socialize this a little bit: https://github.com/chainguard-dev/policy-catalog/pull/81

https://chainguard-dev.slack.com/archives/C02SD39C6BW/p1673391389358379

I also realized that we may have docs pages that may be missing issuer/subject checking in embedded samples, and so I wonder if this might be an opportunity to not only audit the docs for those, but also to potentially have them reference policies from the catalog

**Comment by mattmoor** [comment]
cc @amdawson @k4leung4 as FYI

**Comment by ltagliaferri** [comment]
Partially completed by https://github.com/chainguard-dev/edu/pull/259, need to make sure in-progress docs bring this in too
