### ISSUE TITLE
OCI tutorial

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#261]
Write up on OCI

**Comment by sheesh** [comment]
Draft finished! https://docs.google.com/document/d/1xcC_X5cYcX-xY6KcMWKjNg5irQiAfAPQs0_KSV3x1Z4/edit#

There are a few more things I'd like to add once I get answers from Josh about the OCI next week, but I aimed to create a draft that stands on its own as is. 

This draft just provides an overview of the OCI and its specifications. I'd like to work on an article that talks specifically about OCI artifacts and draws more on Dan's Medium post. 

I plan on asking Erika for a review next week. I also need a walkthrough of the proper workflow for adding this to the repo.

**Comment by sheesh** [comment]
Reviewed by @erikaheidi -- will publish today!

**Comment by sheesh** [comment]
This is ready to publish, but need to determine which directory should house it. I've started a related info architecture discussion here: https://docs.google.com/document/d/1V3XX0Nmz071fIQMB2SCkCpWPP2hj4oROuLF9Ky9y_Zo/edit#heading=h.fvd0gcjx9yu1

**Comment by sheesh** [comment]
Published. We've decided to house it an OCI folder inside open source. We'll be discussing info arch changes next week.
