### ISSUE TITLE
Title-case image names in Chainguard Images Reference

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/edu#267]
**Describe the bug**

Image names listed at [`Chainguard Images Reference`](https://edu.chainguard.dev/chainguard/chainguard-images/reference/) are styled weirdly, with uppercase letters:

<img width="278" alt="Screenshot 2023-01-13 at 9 43 20 AM" src="https://user-images.githubusercontent.com/210737/212347134-dc119623-875a-4295-95da-2459fd4d8299.png">

I couldn't find any place this was explicitly spelled out, so I assume it's some default capitalization. Is there some way to override it?

**To Reproduce**

https://edu.chainguard.dev/chainguard/chainguard-images/reference/

**Expected behavior**

Ideally these would look like:

- `alpine-base`
- `bazel`
- `cc-dynamic`

(lowercase, probably monospace font)

**Screenshots**

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser: Chrome
 - Version 108.0.5359.124 (Official Build) (arm64)

**Additional context**

**Comment by ltagliaferri** [comment]
Yeah, our theme is title casing things in menus and navs, we'll do some digging around this, thanks
