### ISSUE TITLE
Resource: How to use cloud discovery in Chainguard Enforce

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#286]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:**

How to use cloud discovery in Chainguard Enforce

**Description:**

A standalone guide outlining how to use Enforce's new `discover` feature

**Comment by ltagliaferri** [comment]
Does this issue refer to https://github.com/chainguard-dev/edu/pull/309 or something else?

**Comment by SharpRake** [comment]
> Does this issue refer to #309 or something else?

Yes it does, this can be closed.
