### ISSUE TITLE
Standalone Agentless tutorial

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#287]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:**
"Getting started with Agentless Connections in Chainguard Enforce"

**Description:**
Academy's information on agentless Enforce is scattered across a few resources that don't all clearly indicate that they cover Agentless. I think a standalone onboarding tutorial that walks readers through setting up and using Agentless would be useful.

**Comment by ltagliaferri** [comment]
How urgent is this @SharpRake ? Is this a candidate we can take off of the Q2 board?

**Comment by SharpRake** [comment]
> How urgent is this @SharpRake ? Is this a candidate we can take off of the Q2 board?

Not urgent at all, I think we can take it off without worry :+1:

**Comment by SharpRake** [comment]
closing this issue because of [agentless sunsetting](https://docs.google.com/document/d/11gT2pwfasvzIQbtg0GQqTGKL0ojhexNrEi7gUm863k4/edit#heading=h.od18w6wsqlib).
