### ISSUE TITLE
Add SLSA Audit Content to Chainguard Academy

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/edu#293]
Potentially add SLSA audit content to chainguard academy.

**Describe the solution you'd like**
A section on SLSA audits derived from recent SLSA audits that chainguard staff have performed on open source software projects.

**Describe alternatives you've considered**
Don't add it :)
Add it later :)

**Comment by jspeed-meyers** [comment]
I'll wait for @sheesh to add a SLSA tutorial section (#350)  and THEN I'll put in a PR here.

**Comment by ltagliaferri** [comment]
Would you still like to add this into Academy @jspeed-meyers ?

**Comment by jspeed-meyers** [comment]
@ltagliaferri, I've actually decided that I'm not sure this is that useful a contribution, at least right now. I would propose closing this issue. I think SLSA has turned out not to be as high a priority as I previously thought.
