### ISSUE TITLE
Academy V2 redesign 

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#305]
Updating the design and UX of Academy based on these recommendations: https://docs.google.com/presentation/d/1N-0eW2WXBMrYyQ3dc7QpzHuuPGhY4YfxiGSETnghL4E/edit#slide=id.g1929e4c1f25_0_196

Working with Kim and others to determine best approach to implementing new design.

**Comment by kimsterv** [comment]
Current status is that we're waiting on Travers to return to review design and offer minor suggestions to match the visual design of the new site in progress. Next step is to hire a contractor to implement the changes.

**Comment by sheesh** [comment]
Travers is aiming to have polished designs ready by mid march. I had a first call with Toptal and now need approval to put down a $500 refundable deposit to proceed with contractor interview process.

**Comment by sheesh** [comment]
Deposit is submitted and I've continued with hiring process. Toptal recommends we have designs finished before interviewing contractors, as these will influence the contractor's time estimate. I will resume the interview process once we have the designs ready, aiming for mid March.

**Comment by sheesh** [comment]
My feedback for Travers's design is here: https://docs.google.com/document/d/1L9fj6VzaZVS4w__abJFcrZ_3kgHT30QkDNE2wvlLacM/edit#

Will discuss with team on Tuesday (3/14) to finalize and submit to Travers then.

**Comment by sheesh** [comment]
Refined feedback with team input here: https://docs.google.com/document/d/1L9fj6VzaZVS4w__abJFcrZ_3kgHT30QkDNE2wvlLacM/edit#

Will send to Travers once review by Lisa.

**Comment by ltagliaferri** [comment]
We have final designs and are moving to hiring the contractor stage

**Comment by sheesh** [comment]
Job description is now live: https://portal.toptal.com/jobs/VjEtSm9iLTMzMDA3Mg?utm_medium=email

We hope to hear about candidates in the next few days. 

Finalized designs are here: https://www.figma.com/file/hlminFMUGXds23binoDsTg/Chainguard-Academy-2.0?node-id=0-1&t=395o8hiIwBkSjBIU-0

**Comment by sheesh** [comment]
Interviewing two candidates next Monday, 4/3.

**Comment by sheesh** [comment]
Only one candidate was potentially suitable, but the estimated timeline (3 months) and input from Phil made us reconsider our approach.

I've rescoped the job as updating/customizing the current Hugo theme with HTML/CSS, which Phil says should take around 60-100 hours. If necessary, we can consider React for implementing search and code snippets, but I don't want that to become a blocker for updating our templates. Will update once I hear from new applicants.

**Comment by sheesh** [comment]
Toptal acknowledged my request to rescope the job, but then sent me two candidates who responded to the original job posting that focuses React. I've reached out to ask them again to change the job description to focus on updating the theme with HTML/CSS.
