### ISSUE TITLE
Add Non-Security, Non-License Use Cases to SBOM Material

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/edu#310]
@syotfs and I have considered the idea of adding non-security, non-license SBOM use cases to the Academy. One use case I've been interested in relates to organizations using SBOMs to identify open source software projects that are important to their products and using that knowledge to guide donations and donation size to a set of open source software projects. eBay is currently pursuing SBOMs to achieve this objective among others. I'm sure @syotfs has some other ideas too.

**Describe the solution you'd like**
A sub-section in an area related to SBOMs (we are flexible on where exactly) describe these non-security, non-license use cases.

**Describe alternatives you've considered**
Not adding anything beyond security and license use cases.

**Additional context**
This is just a proposal. We defer to @sheesh since her recent SBOM work has been excellent and we see this merely as a small complement to what she has done. If @sheesh and @ltagliaferri are amenable, Michael and I are glad to put in an initial PR.

**Comment by ltagliaferri** [comment]
Sounds good to me!

**Comment by sheesh** [comment]
I love this idea. We now have [an SBOM index](https://edu.chainguard.dev/open-source/sbom/) where you could add the articles. And we could certainly add information to the SBOM overview to include some of this info too. Let me know if I can help!

**Comment by jspeed-meyers** [comment]
Thank you, @sheesh and @ltagliaferri.

@syotfs, how would you like to proceed?
