### ISSUE TITLE
Possible Migration Plan

### ISSUE THREAD

**Issue by ltagliaferri** [chainguard-dev/edu#314]
The bigger investment towards the larger vision is where we look at a migration to a more extensible/customizable stack.  I don’t think this is a huge project to replicate what we have but I would hesitate on using a contractor because it’s more complex, it’s harder to transfer state in-house, there’s probably more maintenance involved, and it’s probably harder to secure the same contractor consistently as work is needed.  So continuing to go to a contractor would include ramping them up each time we wanted to make a big change.Again, off the cuff but my advice is to break it up into pieces:

* How long to recreate what we have now on a new stack?
* What do we want to add in prioritized order (e.g., robust interactive terminal, courseware, potentially certification). 
* What are the very rough time estimates for each of these features?
* What will the ongoing work be to keep this new stack running?  Monitoring, CI/CD, oncall/playbooks, etc….  I don’t think all of this is needed to launch but there will always be some background work going to keep it running.

**Comment by sheesh** [comment]
Backlogging this for now as the V2 redesign will not involve a migration. This will be good to reconsider later in the year as we plan out course/certification experiences.

**Comment by ltagliaferri** [comment]
We may eventually want a DB but otherwise this is addressed by V2
