### ISSUE TITLE
Update docs in Academy to drop Alpine examples and replace with Wolfi

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#315]
Some of the examples reference Alpine. We need to update them to use Wolfi.

Drop references to alpine-based images since they are all wolfi based now, and try to clarify the ecosystem so users understand better what is wolfi and what are chainguard images.

**Comment by ltagliaferri** [comment]
Enforce docs can also include Chainguard Images instead of Alpine, such as [Enforce Signing](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-signing/getting-started-chainguard-enforce-signing/) cc @SharpRake
