### ISSUE TITLE
Suggestion - Add section on using a proxy in images section.

### ISSUE THREAD

**Issue by ryryryano** [chainguard-dev/edu#341]
**Describe the bug**
Recently, I've been supporting a group that needed help with getting Chainguard images and Wolfi Packages through a corporate proxy.  It was suggested that I open up this issue to see if we could provide something for folks in a similar situation.  

Info for getting chainguard images through a proxy:
TLDR, allow access to cgr.dev & ghcr.io.
Slack thread: https://chainguard-dev.slack.com/archives/C0322APD4LU/p1675378122595339

Info for getting Wolfi packages through a proxy:
https://docs.google.com/document/d/1b5N21NbLZJ-oWiH5A7wmkhOskK1mQUPFJvPBzUrtK-g/edit#

Happy to work with the team on this effort or help produce something more formal than my hacked-together notes.

**Comment by ltagliaferri** [comment]
Building off of [Network requirements](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements/)

**Comment by ltagliaferri** [comment]
@jamonation plans to make an Images Network Requirements page for this

**Comment by ltagliaferri** [comment]
@jamonation is creating an Images Network Requirements page combining this issue and https://github.com/chainguard-dev/internal/issues/1822
