### ISSUE TITLE
Academy Terminal Design/Eng touch up

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#362]
Reqs are here: https://docs.google.com/document/d/15MSnleoabxeWi9edxwxZ0uqka-iMc3g2dFD3f1mUmq0/edit#heading=h.apgyfe8vvk9c

**Comment by sheesh** [comment]
These designs will be included in the engineering work being contracted out to Toptal. 
See other ticket for more info:  https://github.com/chainguard-dev/edu/issues/393

**Comment by ltagliaferri** [comment]
Can we close this and track along with overall Academy designs / contractor hiring?
