### ISSUE TITLE
Add policy-controller section to Edu sigstore open source page

### ISSUE THREAD

**Issue by amdawson** [chainguard-dev/edu#366]
As part of our goal to be louder about policy controller, we should include it in the sigstore section of our edu/open source docs

https://edu.chainguard.dev/open-source/sigstore/

quick examples can probably be pulled from OSS:
- how to deploy policy controller
- labeling namespaces for enforcement
- how to define and deploy a policy, define a glob
- how to validate keypair and keyless signatures

**Comment by ltagliaferri** [comment]
cc @sheesh some other ideas for Policy Controller docs

The policy controller section is live here: https://edu.chainguard.dev/open-source/sigstore/policy-controller
