### ISSUE TITLE
Enforce Documentation: The right way to work with SBOM attestations in Enforce

### ISSUE THREAD

**Issue by amdawson** [chainguard-dev/edu#371]
We have had many customers struggle with sbom attestations in enforce. Multiple customers have asked very directly:
- what's the right way to do sbom attestations in enforce? I can't get my sboms ingested, i don't know if I should do cosign attest, attach, or upload. how do I verify? what about predicate types? 

I think we need a page in the Enforce docs on working with sboms. Guidance should be:
- the formats we understand and ingest (spdx, cyclone, other?)
- how to properly do the attestation with cosign (i think it's cosign attest)
- the fact that today, you have to have a policy defined to validate sbom attestations for enforce to ingest it (this should change at some point to be automatic)

**Comment by amdawson** [comment]
shopify, lexis-nexis, and others have asked about this

**Comment by amdawson** [comment]
<img width="373" alt="Screenshot 2023-02-13 at 12 31 10 PM" src="https://user-images.githubusercontent.com/8444505/218529910-46b9b1dd-8503-45b9-b6be-ac44d0e40f0a.png"> shopify

**Comment by amdawson** [comment]
<img width="614" alt="Screenshot 2023-02-13 at 12 32 54 PM" src="https://user-images.githubusercontent.com/8444505/218530261-247ccb8b-7454-4bc7-97c1-91c69a6ef41f.png">

**Comment by amdawson** [comment]
related/dupe: https://github.com/chainguard-dev/mono/issues/7663

**Comment by k4leung4** [comment]
doc for cosign attach vs attest 
pr soon

**Comment by ltagliaferri** [comment]
https://github.com/chainguard-dev/edu/pull/476

**Comment by SharpRake** [comment]
> #476

NVM that PR, see #493
