### ISSUE TITLE
Cloudevents authorization guide

### ISSUE THREAD

**Issue by jamonation** [chainguard-dev/edu#372]
**What topic are you requesting a resource about?**
* Enforce

**Proposed title:**
How to Authenticate Incoming Enforce Cloudevents

**Description:**

We need a page with details on how to verify the `Authorization: bearer ....` token that comes with cloud events from Enforce.

**Comment by jamonation** [comment]
cc @mattmoor for more information about how to proceed.

**Comment by ltagliaferri** [comment]
Closing as we are collapsing this into https://github.com/chainguard-dev/edu/issues/229
