### ISSUE TITLE
Create terminal environment(s) for policy tutorials

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#396]
Create terminal environment for policy tutorials to support [Policy Controller Initiative](https://docs.google.com/document/d/1YhAF_q4u8Rmn52cvqXrT6H19tFPNWQ3S5IP7gngL7PI/edit#) 

Jamon to decide whether one image for all tutorials (with users manually adding the policy) or individual images preloaded with each policy. 

@jamonation let me know if you already created this issue -- i didn't see it.

**Comment by sheesh** [comment]
Jamon demoed a working version of terminal with policy controller today! Looked great! 

Some long load times we may need to look into.

**Comment by jamonation** [comment]
I think we can close this - there are images for the various policy-controller tutorials listed at the end of README.md now
