### ISSUE TITLE
Terminal UI blocks clicks next to it on background page

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/edu#405]
**Describe the bug**

**To Reproduce**
1. Go to https://edu.chainguard.dev/chainguard/chainguard-images/how-to-use-chainguard-images/
2. Observe popup terminal
3. Try to click on one of the sidebar items to the left of the popup terminal (e.g., Ruby, Rust, SDK)
4. Can't click

**Expected behavior**

I'd expect to be able to click outside the terminal

**Screenshots**

<img width="898" alt="Screenshot 2023-02-22 at 3 05 52 PM" src="https://user-images.githubusercontent.com/210737/220747398-685c61d3-b517-4c18-9000-84c80cc8e9cd.png">

**Desktop (please complete the following information):**

 - OS: macOS
 - Browser Chrome 
 - Version 110.0.5481.100 (Official Build) (arm64)

**Comment by ltagliaferri** [comment]
@jamonation looks like there is a bug with the terminal expanding past its end. @sheesh for visibility with Academy v2
