### ISSUE TITLE
Update Chainguard Images Overview page to show a list of image tutorials

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#435]
Update [this page](https://edu.chainguard.dev/chainguard/chainguard-images/overview/) to include a list of "Getting Started" guides already published.

After working on a few different "getting started" guides, we noticed that the process is very similar and can be extrapolated to other language ecosystems. Giving more exposition to the current guides (PHP, Node, Python, Go...) in the main / entry page of Chainguard Images documentation will serve as universal examples for other images and ecosystems.

**Comment by ltagliaferri** [comment]
cc @sheesh — this can maybe be done through tag / topic paging

**Comment by erikaheidi** [comment]
closing this to free up space in the project.
