### ISSUE TITLE
Implement tags/categories on Academy 

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#440]
Lisa has set up tagging capacities on Academy, now they need to be implemented. 

Once we've successfully implemented test tags, I'll create a tag list and documentation for adding more.

**Comment by sheesh** [comment]
List of tags/categories to be added and logic for both:
https://docs.google.com/document/d/1ZiHueFs6Qn1uedvzbLmnLc3UzScremo-gZWk8N8jR34/edit#

**Comment by sheesh** [comment]
Ready to be reviewed
#469

**Comment by sheesh** [comment]
Documentation added to wiki and ready to be reviewed
https://github.com/chainguard-dev/wiki/blob/main/content/en/docs/products-and-OSS/Chainguard-Academy/style-guide/academy-tags.md

**Comment by ltagliaferri** [comment]
Can you add tags to the README too? https://github.com/chainguard-dev/edu#readme

**Comment by sheesh** [comment]
Done!

**Comment by sheesh** [comment]
Sent new PRs for tags with proper letter case. Image reference docs are the only tutorials that still need to be tagged.
