### ISSUE TITLE
Implement versioning on Academy 

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#441]
The Hugo Doks theme has versioning capacity, but it has not been implemented. 

I will see if we can implement versioning into our tutorials and document if successful. Otherwise, I will look into other options for enabling versioned tutorials.

**Comment by smythp** [comment]
This might be difficult given our version of Doks. Have you looked into it?

**Comment by smythp** [comment]
Iceboxing 🧊 It's a can of worms with our current Doks version.

**Comment by smythp** [comment]
I'm going to close this unless anyone has objections. This would only really be possible after updating the doks version on Academy which isn't going to happen anytime soon given how custom the site is now.
