### ISSUE TITLE
Enforce network requirements doc needs update

### ISSUE THREAD

**Issue by amdawson** [chainguard-dev/edu#444]
So it turns out that Enforce SaaS needs access to image registries to do admission control and also ingest sboms etc. The [network requirements doc](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements/) only says that the enforce agent needs access.

In the doc, the section that describes access requirements for image registries says:
`The Enforce agent needs access to any registry or registries that are configured for your cluster or containers so that it can validate images and policies.
Whether they are public or private, ensure that outbound connections from the Enforce agent (running in the gulfstream namespace) are permitted to your configured registry or registries. Also be sure to allow the corresponding return traffic if you are using symmetric firewall rules.`

Apparently the inbound access from enforce SaaS is also required for the customer registry endpoint as well, not just the k8s cluster. See this issue for more detail: https://github.com/chainguard-dev/customer-issues/issues/148

not immediately urgent but we should update the doc.

**Comment by ltagliaferri** [comment]
@jamonation can you take a look at this and update the doc

**Comment by jamonation** [comment]
Should be all set @amdawson - I split the registry access section into two parts, one for agentful and one for SaaS: https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/network-requirements/#image-registry-access
