### ISSUE TITLE
Enforce egress CIDR blocks, allow list for access from client clusters

### ISSUE THREAD

**Issue by k4leung4** [chainguard-dev/edu#451]
The Enforce egress CIDR blocks specify what IPs Enforce will communicate from to client's k8s clusters.
These CIDR blocks are now available via chainctl in v0.1.83

```
ks-MBP:999-monitoring k4leung$ chainctl clusters cidrs list
35.230.121.20/32
34.132.193.40/32
35.237.242.37/32
```

This information was previously noted via the discovery function, https://github.com/chainguard-dev/edu/blob/main/content/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-discovery-onboarding/index.md?plain=1#L166-L170

Not sure if this information should be mentioned in other places to ensure that users are aware that these CIDR blocks need to be allowed list so Enforce can communicate to their cluster.

There is also work in progress to surface this information via Terraform, so it can be directly be used during k8s cluster creation allow listing these CIDR blocks.

**Comment by ltagliaferri** [comment]
@jamonation should we add this to the Networking doc too?

**Comment by jamonation** [comment]
I've got this being pulled in automatically on the network page using a shortcode:

`{{< blurb/enforce-ips >}}`

So anywhere on Academy that needs the list of IPs should be ok to just embed that and it will render them inline.

**Comment by ltagliaferri** [comment]
@jamonation I'm implementing this in the discovery doc, but do you think we would be able to format it to be bullets like how Mark formatted it previously?

<img width="530" alt="Screenshot 2023-03-18 at 3 14 16 PM" src="https://user-images.githubusercontent.com/5977693/226131421-b604a670-11dd-4874-9892-dbac589f42a2.png">
