### ISSUE TITLE
Selecting a Secure Base Image tutorial

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#453]

**Comment by jspeed-meyers** [comment]
I created a draft [here](https://docs.google.com/document/d/1DdGpZf5pGIfbRWxA87wYrdIiCvcsWDcIj6OhK7ovGCg/edit?usp=sharing).

@sheesh, any feedback is welcome but not necessary.

I will work on filling in this outline next week.

**Comment by sheesh** [comment]
This is a great outline - thanks for sharing! Would love to see the draft when it's ready. :) 

Also, I wonder if we might want to politely plug Chainguard Images at the end of this tutorial (and maybe the other tutorials in this series)? I don't want to turn off readers, but some folks interested in the topic may also be interested in Chainguard Images as a solution? 

Jamon has done something similar in plugging Enforce at the end of his policy catalog tutorials: https://edu.chainguard.dev/open-source/sigstore/policy-controller/how-to-install-policy-controller/#options-for-continuous-verification

Just a thought. Let me know what you think.

**Comment by jspeed-meyers** [comment]
A polite plug sounds good to me. I'll work it into the draft :) I'll send you a full draft later this week.

**Comment by sheesh** [comment]
Ok, great! And only if you feel comfortable doing it. If you do, I would recommend making it clearly separate from the rest of the educational content, such a quick plug at the end of the article.

**Comment by jspeed-meyers** [comment]
@sheesh, full draft [here](https://docs.google.com/document/d/1DdGpZf5pGIfbRWxA87wYrdIiCvcsWDcIj6OhK7ovGCg/edit?usp=sharing).

Proposal to you: I would suggest that you review it first (and squeeze out the bugs 🐛 ), let me revise it, and then (B) send it to someone such as Adrian with deep knowledge of container images and base images to also provide a review. wdyt?

**Comment by sheesh** [comment]
Awesome, your plan sounds great! I'll have comments to you by tomorrow. Thanks!

**Comment by jspeed-meyers** [comment]
I'm taking tomorrow off, so if I seem slow, it's not personal. I'll be back working on Monday :)

**Comment by sheesh** [comment]
Another John Speed hit! Thanks for letting me read. It's a great motivator for working on the rest of the series. Everything looks good to me -- as you saw, I just added a few comments with my editorial preferences, but you can take them or leave them!

**Comment by jspeed-meyers** [comment]
I took them :) !! Thanks for the review. LMK if and when my review on the sections can be constructive.

**Comment by jspeed-meyers** [comment]
@sheesh, do you want me to put in a PR with this section? If so, where should this .md file be located?

Additionally, is there anything else you want me to do? I didn't want to leave you hanging :)

JS

**Comment by sheesh** [comment]
That would be great! I would put it in the `software-security` directory, if that makes sense to you. 

Other projects have delayed my planned tutorials for this mini course, but I will check in with you as soon as I have them going. Thanks again for this terrific tutorial!
