### ISSUE TITLE
enforce: add documentation for the enforcer options during cluster installation

### ISSUE THREAD

**Issue by hectorj2f** [chainguard-dev/edu#495]
**What topic are you requesting a resource about?**
* Chainguard product

**Proposed title:**

Installing Chainguard with chainctl configuring your Enforcer Options
**Description:**

Add documentation about the new enforcer options available when installing a tenant cluster.

**Comment by ltagliaferri** [comment]
Does #519 close this, or did you want to add something else?

**Comment by hectorj2f** [comment]
Yep, we are good for now. We might need to add a new enforcer option around next week. But we are good.
