### ISSUE TITLE
Clarify the UIDP (in particular, the subjects or the actors) in Eventing docs

### ISSUE THREAD

**Issue by tcnghia** [chainguard-dev/edu#522]
**Is your feature request related to a problem? Please describe.**
Since UIDP fields are often very opaque, it is more difficult for users to guess the meaning by themselves. An example is https://chainguard-dev.slack.com/archives/C038ALHB9H9/p1679692487658039 where the user was confused.

**Describe the solution you'd like**
We should clearly document what the UIDPs refer to in the eventing docs.

**Describe alternatives you've considered**
I couldn't come up with an alternative.

**Additional context**
https://chainguard-dev.slack.com/archives/C038ALHB9H9/p1679692487658039

**Comment by tcnghia** [comment]
cc @jedsalazar

**Comment by ltagliaferri** [comment]
@tcnghia we don't have access to those conversations on the edu team, could you either add one of us to the channel or paste the conversation in a google doc we have access to? Thank you!

**Comment by tcnghia** [comment]
It's a short conversation, so I screen shot here

![image](https://user-images.githubusercontent.com/138266/228107717-e7a574be-095d-43cb-bf56-a3574a4f5eb0.png)

**Comment by ltagliaferri** [comment]
https://chainguard-dev.slack.com/archives/C040R8V1BG9/p1679970394103779

**Comment by ltagliaferri** [comment]
@jamonation — can we add the explanation of the UIDP to the [Events doc](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/chainguard-enforce-events/) or should that be done in the code repo?

**Comment by jamonation** [comment]
@ltagliaferri I think it has to be done in the code repository for now, since that file gets generated via a go template.

I suppose another option would be extending that notice/warning partial logic a bit to be more generic, and have all the text for events live here in a file like `data/events.yaml`. But this approach seems a bit too hackish?
