### ISSUE TITLE
Accidental German flag on "How to Inspect and Verify Fulcio Certificates"

### ISSUE THREAD

**Issue by znewman01** [chainguard-dev/edu#524]
**Describe the bug**
The page "How to Inspect and Verify Fulcio Certificates" has a German flag in the middle of the code output. (also a weird "AB" emoji)

**To Reproduce**
https://edu.chainguard.dev/open-source/sigstore/fulcio/how-to-inspect-and-verify-fulcio-certificates/

**Expected behavior**
No German flag

**Screenshots**

![Screenshot 2023-03-27 at 3 11 43 PM](https://user-images.githubusercontent.com/873857/228042888-2b86bcaf-11cc-4693-bc45-31b2915067bd.png)

**Desktop (please complete the following information):**

**Additional context**
Assume this is the emojification engine being a little too aggressive. It probably shouldn't run at all inside code blocks.

**Comment by ltagliaferri** [comment]
It's probably a good idea to remove the real email here anyway, let me edit this page and I opened another issue about emojis in code blocks. Thanks!
