### ISSUE TITLE
Enable new nav bar titles that are separate from body titles for docs

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#534]
We would like to have the option to create nav bar-specific titles that are separate from the title used in the body of a doc. We think this would be achievable by creating a nav bar title label ("shortTitle") in the metadata posted at the top of the doc file. 

For example: 
title: "this is a long title" 
shortTitle: "Short title"

cc @SharpRake and @ltagliaferri in case you want to add anything!

**Comment by SharpRake** [comment]
I figured out how to enable `linktitle` fields in the Hugo front matter: https://github.com/chainguard-dev/edu/pull/602
