### ISSUE TITLE
Melange Pipelines page doesn't include go/install and others

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/edu#569]
**Describe the bug**

https://edu.chainguard.dev/open-source/melange/melange-pipelines/ lists built-in pipelines in melange, which are defined here: https://github.com/chainguard-dev/melange/tree/main/pkg/build/pipelines

The page doesn't include a few recent additions:
- `go/install`
- `go/build`
- `ruby/build`
- `ruby/clean`
- `ruby/install`

**To Reproduce**
1. Go to https://edu.chainguard.dev/open-source/melange/melange-pipelines/
2. Don't see `go/install` and others

**Expected behavior**

All the pipelines defined in https://github.com/chainguard-dev/melange/tree/main/pkg/build/pipelines (incl subdirectories) should have an entry in the list

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 111.0.5563.110 (Official Build) (arm64)

**Additional context**

`go/*` pipelines were added in December, `ruby/*` ones added in February.

If it's possible to automate these when a melange release happens, that'd be great. If not, we can make it part of the melange release playbook if there are instructions to regenerate these ourselves.

**Comment by erikaheidi** [comment]
We have de-prioritized efforts around documenting melange and apko to focus on Chainguard Images. So the pipelines docs are not running on schedule, there is a command to generate them but we haven't set up a workflow like we did with the images reference docs.

I can PR a manual update to get these up ASAP, and then we can create a separate issue for the automation and discuss priorities again for this quarter.

**Comment by erikaheidi** [comment]
PR with manual update: https://github.com/chainguard-dev/edu/pull/574

**Comment by erikaheidi** [comment]
This has been merged, if we want to automate this it will need a bit more work so a separate issue should be created (trying to keep priorities in mind).
