### ISSUE TITLE
Improve Syntax Highlighting

### ISSUE THREAD

**Issue by erikaheidi** [chainguard-dev/edu#57]
The current syntax highlighting theme doesn't have a good contrast on dark mode. Ideally, let's use the theme toggle button to also change the syntax highlighting theme when users change from light to dark mode.

**Comment by ltagliaferri** [comment]
@erikaheidi — I know you made some improvements here, are you satisfied with where we have landed?

**Comment by erikaheidi** [comment]
I just had a look now, in dark mode I think it still could be better. A different syntax highlighting theme may be able to fix it.

**Comment by ltagliaferri** [comment]
Let's add this to the reqs / specs for the Hugo dev

**Comment by ltagliaferri** [comment]
Improvements made with V2 launch
