### ISSUE TITLE
Maximum Image Age policy tutorial 

### ISSUE THREAD

**Issue by sheesh** [chainguard-dev/edu#576]
Create a Maximum Image Age policy tutorial for an Enforce Solutions page

Working draft here: https://docs.google.com/document/d/19HH4JdM6Oj2TAUfwakcpZsJY94JaO5fg5cJDvCIJ9hU/edit

Part of this ticket: https://github.com/chainguard-dev/internal/issues/1257

**Comment by ltagliaferri** [comment]
Closed by https://github.com/chainguard-dev/edu/pull/580
