### ISSUE TITLE
Images reference pages have an odd top nav widget

### ISSUE THREAD

**Issue by patflynn** [chainguard-dev/edu#632]
I was just looking at our images reference docs such as the [gradle image docs](https://edu.chainguard.dev/chainguard/chainguard-images/reference/gradle/overview/), and I noticed that the display of a nav widget seems to not have a dark mode equivalent. See attached screenshot below.  Once I noticed the widget I tried it's various links ('Reference', 'Chainguard Imagse', and 'Product'), and I struggled to make sense of what they were doing there or where they were taking me. 

![image](https://user-images.githubusercontent.com/7862557/234286532-d8461a84-2a57-49f5-b0d2-b1f641426747.png)

**Comment by ltagliaferri** [comment]
@patflynn those are tags. We have a big design update currently in progress, which we are tracking at https://github.com/chainguard-dev/edu-private The tags styling are already changed in that repo, which we will cut over at launch.
