### ISSUE TITLE
More assumed identities examples

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#671]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:**

These would closely follow the format of the ~~(soon to be published)~~ [GitHub Actions example](https://edu.chainguard.dev/chainguard/chainguard-enforce/iam-groups/enforce-github-identity/).

**Description:**

I'm thinking examples of setting up identities to be assumed by:

- [ ] GitLab
- [x] Buildkite
- [ ] Cloudbuild
- [ ] CircleCI
- [x] Bitbucket
- [x] Jenkins

This list may change depending on the scope of each given example, though the existing Actions example will serve as a useful template. These examples should be based off those found [here](https://github.com/mattmoor/terraform-playground)

**Comment by jamonation** [comment]
Added bitbucket to the list, since I got it working with terraform.

**Comment by ltagliaferri** [comment]
We are good to mark as done

**Comment by ltagliaferri** [comment]
Reopening this for GitLab cc @strongjz
