### ISSUE TITLE
Enforce Docs: Add Information on Rate of Clusters (Resources?) Being "Seen"

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/edu#680]
**Is your feature request related to a problem? Please describe.**

Chainguard Academy docs currently do not explain the rate at which clusters and other resources are "seen." See screenshot for more context. A user curious about the rate at which other clusters are "seen" will have to contact the CE team right now, creating additional workload for that team.

**Describe the solution you'd like**

Explanation in the Enforce product documentation explaining the rate at which clusters and other resources are seen.

**Describe alternatives you've considered**

Not adding anything or waiting to add something until there is a customer request are also possibilities.

**Additional context**

![Screenshot 2023-05-10 at 8 42 41 AM](https://github.com/chainguard-dev/edu/assets/54914994/834f3fe3-c4da-48c1-bcc5-3a6b4a7f0e02)

cc @SharpRake

**Comment by ltagliaferri** [comment]
Maybe this can be added to the reference section ? https://edu.chainguard.dev/chainguard/chainguard-enforce/reference/

cc @jamonation also
