### ISSUE TITLE
Overview of SBOMs in Enforce

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#730]
**What topic are you requesting a resource about?**
* **Chainguard product**
* Open source related
* Conceptual security related
* Other (please describe)

**Proposed title:**

TBD (potentially "Overview of SBOMs in Enforce")

**Description:**

https://docs.google.com/document/d/1QkhXVqFKyyndinqYn9iEetYjiH-DkIYtvRsJaeYmmDY/edit?usp=sharing

Part of resolving (https://github.com/chainguard-dev/internal/issues/1598), this will serve as an introduction to SBOMs in Enforce, including the requirements for an SBOM to be ingested.

**Comment by narayan-iyengar** [comment]
Do we have a target date for SBOMs in Enforce docs?

**Comment by SharpRake** [comment]
> Do we have a target date for SBOMs in Enforce docs?

I think I can get some working docs published by 6/23, depending on reviewer availability

**Comment by SharpRake** [comment]
@narayan-iyengar Yes! these are completed
