### ISSUE TITLE
images reference list should be lowercased

### ISSUE THREAD

**Issue by imjasonh** [chainguard-dev/edu#749]
**Is your feature request related to a problem? Please describe.**

The list of images at https://edu.chainguard.dev/chainguard/chainguard-images/reference/ sometimes has weird formatting, due to things that are acronyms and are presented in title case.

Examples from the page above the fold:
- Argocd-Repo-Server
- Aws-Cli
- Aws-Efs-Csi-Driver

**Describe the solution you'd like**

Lowercase all the strings, possibly in some monospace font so it's clear they're identifiers and not Things-People-Should-Read.

For example:
- `argocd-repo-server`
- `aws-cli`
- `aws-efs-csi-driver`

**Describe alternatives you've considered**

We could also try to detect acronyms and present them:
- ArgoCD-Repo-Server
- AWS-CLI
- AWS-EFS-CSI-Driver

...but this could be tricky to get right, and could be misleading since the images are actually fetched by the lowercase form (`cgr.dev/chainguard/aws-cli`), and copypasting the uppercase form would result in a confusing error.

**Additional context**

I can try to make this change myself as an attempt to understand how these pages get generated, if someone can point me to some code 🙏

**Comment by ltagliaferri** [comment]
We already have this [open issue](https://github.com/chainguard-dev/edu/issues/267), this is automatic in the Hugo theme we are using and we have not been able to prioritize overriding it. We are working on the [V2](https://github.com/chainguard-dev/edu-private), so I would not change any code in the current repo right now. We will try to figure this out if it is not addressed by the V2 updates.

**Comment by imjasonh** [comment]
Oh! Sorry for the duplicate issue, looking forward to V2! 👍
