### ISSUE TITLE
Broken links in the How to Use Chainguard Images article

### ISSUE THREAD

**Issue by stormqueen1990** [chainguard-dev/edu#841]
**Describe the bug**
In the ["How to Use Chainguard Images" article](https://edu.chainguard.dev/chainguard/chainguard-images/how-to-use-chainguard-images/), the following sentence contains two links that point to repositories that don't exist in the chainguard-images GitHub org:
> If your binary is dependent on glibc or musl, take a look at the [glibc-dynamic](https://github.com/chainguard-images/glibc-dynamic) and [musl-dynamic](https://github.com/chainguard-images/musl-dynamic) images.

**To Reproduce**
1. Navigate to https://edu.chainguard.dev/chainguard/chainguard-images/how-to-use-chainguard-images/
2. Scroll down to the end of the "Using the Distroless Base Images" section.
3. Notice that the links to glibc-dynamic and musl-dynamic are both pointing to a non-existent page.

**Expected behavior**
Links point to an existing page or repository.

**Comment by stormqueen1990** [comment]
I was able to find [glibc-dynamic on chainguard-images/images](https://github.com/chainguard-images/images/tree/main/images/glibc-dynamic), and there is also a broken link to musl-dynamic in the glibc-dynamic README.

**Comment by ltagliaferri** [comment]
Hi @stormqueen1990 thank you so much for reporting this issue! We updated the link, and the Dockerfile in the tutorial will also need to be updated, which we will do promptly. The team is working on the best catalog fit for each image and we are discussing this feedback to continue to iterate. Again, thank you for bringing this to our attention.
