### ISSUE TITLE
[apko] Resource: Terraform Provider apko documentation

### ISSUE THREAD

**Issue by denhamparry** [chainguard-dev/edu#845]
**What topic are you requesting a resource about?**

- [x] Chainguard product
- [x] Open source related

**Proposed title:** Getting Started with the apko Terraform provider

We are now using Terraform to build our Chainguard Images. Several people have asked for best practices for building aspects of their images (e.g., `-dev` variants of a custom image) provided within a submodule of the apko Terraform provider.

Being able to provide a walkthrough for this process would be beneficial to people building Chainguard Images, as well as educating best practices to the community.

**Description:**

Links:

- [Chainguard Images Terraform README](https://github.com/chainguard-dev/images/blob/main/TERRAFORM.md)
- [GitHub - Terraform Provider apko](https://github.com/chainguard-dev/terraform-provider-apko)
- [Terraform Registry - apko](https://registry.terraform.io/providers/chainguard-dev/apko/latest)

**Comment by ltagliaferri** [comment]
Thinking to pick an example image to demonstrate how this works, with local testing then ttl.sh

**Comment by denhamparry** [comment]
As a recommendation, maybe we could use a "Hello Inky" application that is a simple web server that renders an `index.html` page. This image can be built and when run would render the page via a port and browser/curl. Ee can then also create the `-dev` variant that allows using `ls`, `cat`, and an editor to change the value within `index.html`.
