### ISSUE TITLE
Image variants pages appear outdated

### ISSUE THREAD

**Issue by eddiezane** [chainguard-dev/edu#876]
**Describe the bug**

The Image variants pages in docs don't seem to be complete.

For example [go](https://edu.chainguard.dev/chainguard/chainguard-images/reference/go/image_specs/) is missing 1.20 and [python](https://edu.chainguard.dev/chainguard/chainguard-images/reference/python/image_specs/) is missing 3.11.

**Additional context**

Do we want to keep these tags there past the August 16th changes?

**Comment by ltagliaferri** [comment]
@jamonation made a first pass with #879

**Comment by ltagliaferri** [comment]
@erikaheidi prepared this doc that captures the amount of work that would need to be involved to resolve this https://docs.google.com/document/d/1OdHI49ZkUqLqeew-p_hFYLzYNnZJM7rIERgEyr45kok/edit

**Comment by ltagliaferri** [comment]
This has been resolved, thanks @erikaheidi
