### ISSUE TITLE
blog post on Images Getting started examples repo

### ISSUE THREAD

**Issue by SharpRake** [chainguard-dev/edu#914]
Creating an issue to track work on a blog post about our repository of demos for Getting started with X Image guides.

**Comment by SharpRake** [comment]
Didn't get this started last week (due to existing + unexpected priorities) but want to work on this this week.

**Comment by SharpRake** [comment]
Made good progress on this in between other tasks last week. Ought to have a draft ready to share soon.

**Comment by SharpRake** [comment]
Put together a (very) rough draft: https://docs.google.com/document/d/1CBpgvirYgltHYZG-1N5Cfbo5hj2_qXfo1l4S7IN5Jd4/edit?usp=sharing

@ltagliaferri to flesh this out a bit I mention the forthcoming Getting Started guides landing page, so we ought to wait on publishing until that work is finished.

**Comment by SharpRake** [comment]
This is ready for review (again)! https://docs.google.com/document/d/1CBpgvirYgltHYZG-1N5Cfbo5hj2_qXfo1l4S7IN5Jd4/edit?usp=sharing

**Comment by ltagliaferri** [comment]
I gave the blog a pass, and recommend [filling out the request form](https://forms.monday.com/forms/7e509203ce3d60fb2cf2667314998fad?r=use1) and reaching out to Tyler on #blog

**Comment by ltagliaferri** [comment]
Mark filled in marketing request and touched base with Tyler, waiting to hear back on next steps

**Comment by SharpRake** [comment]
Received Semrush SEO Writing Assistant draft from Tyler, working to improve SEO before publication

**Comment by SharpRake** [comment]
Final draft is under review, tentative publication around 11/28

**Comment by SharpRake** [comment]
Per the [Marcomm Calendar](https://docs.google.com/spreadsheets/d/1q1jTNRxNBJFO6u9XvoO7YfmkvSk1WVM17c4KCzyJwOY/edit#gid=318984287&range=A154) this is set to fly on 12/4

**Comment by SharpRake** [comment]
this is live: https://www.chainguard.dev/unchained/new-images-guides-on-chainguard-academy
