### ISSUE TITLE
Go image overview: Broken example link

### ISSUE THREAD

**Issue by garrying** [chainguard-dev/edu#918]
**Describe the bug**
Example for the `go` image seems to have been moved or deleted. The example link in [README.md](https://github.com/chainguard-images/images/blob/main/images/go/README.md) is broken at `https://github.com/chainguard-images/images/blob/main/images/go/examples/hello/main.go`

**To Reproduce**
1. Go to https://edu.chainguard.dev/chainguard/chainguard-images/reference/go/overview/
2. Scroll down to `Host architecture example`
3. Click on [examples/hello/main.go](https://github.com/chainguard-images/images/blob/main/images/go/examples/hello/main.go)

**Comment by SharpRake** [comment]
Thanks so much for catching this Garry - I submitted a PR to update this in the chainguard-images repo (where the Image overviews are pulled from) and fixed the link there: https://github.com/chainguard-images/images/pull/1225
