### ISSUE TITLE
BUG: Typo in `CGO_ENABLED` Commaned

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/edu#969]
**Describe the bug**

https://edu.chainguard.dev/chainguard/chainguard-images/videos/static-base-image/

I expect the CG_ENABLED=0  in `RUN CG_ENABLED=0 go build -o /hello /main.go` to be `CGO_ENABLED=0`. Am I missing something?

**Comment by ltagliaferri** [comment]
@amouat can you review this bug and make update if needed?

**Comment by amouat** [comment]
Yeah, it's just a typo. It's correct in the video, so I'm not sure how it got left out.
