### ISSUE TITLE
BUG: Link Now Missing

### ISSUE THREAD

**Issue by jspeed-meyers** [chainguard-dev/edu#970]
**Describe the bug**

In this overview: https://edu.chainguard.dev/chainguard/chainguard-images/reference/go/overview/

The "host architecture example" points to a file at [tests/hello/main.go](https://github.com/chainguard-images/images/blob/main/images/go/examples/hello/main.go) that does not exist any longer.

**Comment by ltagliaferri** [comment]
All overviews are pulling from the [Images repo](https://github.com/chainguard-images/images) via autodocs (any changes we make on our side would be overwritten), I would file the issue there
