### ISSUE TITLE
"Building a Wolfi Package" mentions nonexistant packages.txt

### ISSUE THREAD

**Issue by isker** [chainguard-dev/edu#972]
https://github.com/chainguard-dev/edu/blob/48251583f04aa2e7c4df7de90b326415fa427b33/content/open-source/wolfi/building-a-wolfi-package.md#L436

There is no such file anywhere in https://github.com/wolfi-dev/os.  It may simply be fine to delete this step; a recent PR adding a package did not have to mention it anywhere other than its own file: https://github.com/wolfi-dev/os/pull/4852.

**Comment by ltagliaferri** [comment]
We have recently updated this tutorial, thank you!
