### ISSUE TITLE
Explain infra hierarchy better in enforce (groups etc)

### ISSUE THREAD

**Issue by amdawson** [chainguard-dev/edu#98]
empathy day feedback from ville
I’m creating a group but I just got the email, so I have no idea what a group is, what does it taste like. Wonder if we should give a little blurp here what a group is. Just putting myself in the users shoes and cut&paste are working wonders, but just wondering if this would be a good time to at least give a little blurp about what the user is doing and why

Adam comments:
We should probably give an overview of how the enforce hierarchy maps to k8s and how users should use them.

**Comment by ltagliaferri** [comment]
If this is for the Console UI should there be a ticket there? Otherwise I'll close this out as we have an [architecture diagram and Chainguard Enforce overview](https://edu.chainguard.dev/chainguard/chainguard-enforce/chainguard-enforce-kubernetes/enforce-overview/)
