### ISSUE TITLE
Docs/edu content for bazel rules for apko 

### ISSUE THREAD

**Issue by amdawson** [chainguard-dev/edu#983]
**What topic are you requesting a resource about?**
We are going to publish a bazel rule for apko that allows bazel users to invoke apko to create wolfi based images during the bazel build process. 

Our contractor can do a video and tutorial and basic docs, but we may need to enhance, edit, or crosspost in edu 

**Proposed title:**
Building Wolfi-based container images with Bazel

**Description:**

**Comment by ltagliaferri** [comment]
We published this
