### ISSUE TITLE
Add Enforce Overview and Architecture overview to Getting started docs

### ISSUE THREAD

**Issue by amdawson** [chainguard-dev/edu#99]
Feedback from empathy day:

"I think in general we should have an enforce overview and architecture overview, and a little better explanation of what each part of the onboarding steps do"

My thoughts are a section that explains the basic features of enforce: allows you to implement and enforce security policies on your kubernetes fleet, monitor the status of policies in real time, easily update and distribute policies across clusters, require image signatures, SBOMs, and secure registries, etc.

and also a quick overview of the components:
- enforce platform: a SaaS solution that does blah blah
- enforce agent: lightweight agent that runs on your K8s cluster nodes to distribute policies, continuously monitor the security of clusters, and report information to the enforce platform
- chainctl: a command line utility that lets you manage users, groups, define policies, authenticate to chainguard, and check status of clusters at the command line

**Comment by amdawson** [comment]
I think we should update them - we need to show both agent and agentless mode as well as the Signing service, and of course the style in these is outdated.

I can help create the diagrams but will also need to consult with the eng folks

**Comment by ltagliaferri** [comment]
Here are a few other (messy) drafts I had (with [webhook](https://drive.google.com/file/d/1UYkIV66Kj-g02UHZ8Vaop-kEnUaWEh_r/view?usp=sharing), & [more abstract agent](https://drive.google.com/file/d/170vvxFyK5ObK_LMv7ibCZJACNh_Q8Tzi/view?usp=sharing ), there were some questions around how much to make public, and I still have the original files to bring into the new style, so let me know how I can help move this forward, I know this is top of mind for @jedsalazar

**Comment by ltagliaferri** [comment]
Can we use [slide 27 from the new slide deck](https://docs.google.com/presentation/d/1Awz8Mdi1PwWMpwv79j_XMP5COruuViQPoDSrusD-iLM/edit#slide=id.g1a6f596fd82_0_143) for the diagram?

**Comment by amdawson** [comment]
Yes was gonna say that
